packages: []

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  "@reown/appkit": true
  "@stellar/stellar-sdk": true
  blake-hash: true
  bufferutil: true
  protobufjs: true
  secp256k1: true
  tiny-secp256k1: true
  usb: true
  utf-8-validate: true
